version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "16:00"
    timezone: Europe/Madrid
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - raulcontrerasrubio
  ignore:
  - dependency-name: ajv
    versions:
    - 7.0.3
    - 7.0.4
    - 7.1.0
    - 7.1.1
    - 7.2.1
    - 7.2.4
    - 8.0.4
    - 8.0.5
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.3
    - 5.2.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.1.0
  - dependency-name: api-contract-validator
    versions:
    - 2.2.2
    - 2.2.3
  - dependency-name: helmet
    versions:
    - 4.4.1
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
