language: node_js
os: linux
dist: xenial
node_js:
  - 14
branches:
  only:
    - master
    - stable
services:
  - redis
install: npm install
script: npm test
deploy:
  - provider: heroku
    skip_cleanup: true
    app: quienmedebe
    strategy: git
    api_key:
      secure: $HEROKU_KEY
    on:
      tags: true
      branch: stable
  - provider: heroku
    skip_cleanup: true
    app: quienmedebe-staged
    strategy: git
    api_key:
      secure: $HEROKU_KEY
    on:
      branch: master
