language: node_js
os: linux
dist: xenial
node_js:
  - 14
services:
  - redis
install: npm install
script: npm test
deploy:
  provider: heroku
  skip_cleanup: true
  app: $HEROKU_APP_NAME
  strategy: git
  api_key: $HEROKU_KEY
  if: branch = master
