language: node_js
node_js:
  - 14
services:
  - redis
deploy:
  provider: heroku
  api_key:
    secure: yQ0cGDCuvS0qdcHDTYZ9d1bXZ9JiINMg+0zNLCS89+tINx/njy66tdWCc8LMlUYvEch3QIZ1ZbJuPsDCwdsc+9bR5E4zWgaLIbu163pvWnGrwl58g0ZW0/v2y9KFttaTjxX7iiOqylvD0AjmRrvakSEBl03Z/sPW68txfNoHZUSgaUY65fvmEqtir8YrGtf4UfTl+j8ADRPLNvjRNj41vvLPWIVjNWAkbI2QeAK8sfkBypLIGN4Q6tm0EbsTIB06Wmm413zQhs14pEbFPd/S5zY4cswZOjrwqlaz2eMZtwffNIXDlwfyW/8a6/f/tU48qgJrbedFaRrekJrfyUCW5ymOpGNRSS8z/kwNl6LyJJXHgwrJEdFWSkHB3putW1QJJ2eTWT5DyYaEWduXbfNq9ZhSq2yGv2kqJ8DFCYny76W0+YUSGcJaR5m7353K5hFuv4+hA4YypT+J5iykZZXS52DHZvPBjeM70tlDxudr7fhyTu9d0No3Wfd22UGkrY53bmXv/ah9YdMv6N3SVnNSXYDL09qtjzN0BchfhlETRacQs0UETDfVe0LcQUuu670gdm0WfkmbjzjpgeswQN7jzh4/yMBKBQTzwi+sS36u6Db7HHXHcj3bZvlg4dvfjNG7LCj0ePRWNNsa3ki39ENZonHgBFVr33ZEcGaZOZ/abNw=
