language: node_js
node_js:
  - 14
install: npm install
script: npm test
branches:
  only:
    - master
    - stable
services:
  - redis
deploy:
  - provider: heroku
    skip_cleanup: true
    app: quienmedebe
    strategy: git
    api_key:
      secure: $HEROKU_KEY
    on:
      tags: true
      branch: stable
  - provider: heroku
    skip_cleanup: true
    app: quienmedebe-staged
    strategy: git
    api_key:
      secure: $HEROKU_KEY
    on:
      branch: master
