language: node_js
os: linux
dist: xenial
if: (type = push AND branch IN (master)) OR (type = pull_request AND NOT branch =~ /no-ci/)
node_js:
  - 14
services:
  - postgresql
install: npm install
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm run test:db:migrate
script: npm test
after_success:
  - npm run test:coverage:lcov
  - npm run test:coveralls
deploy:
  provider: heroku
  api_key:
    secure: wqH4ArOezqZgbeqemXBg83Ir2nDPp1dl0SI44nQGMa8t+bRcR9plrgyjXKeXK5Mh8joYB8LUYW4TKTXtRk3neo7G3/zN47o0neXwEYJ9CwK5Q/eqs65dCgd5DgQ8J3hQTph41Vv3EZ/Vlvpcg/8XTo6UiMYxOcuVvmkwHMDm47UZLgOk7bfpkhi+b4+x/IXod7oFjPTdjjQVFzNBNsk4iJ7lzEUKx9EjBNuw3mxFOFS0e/PusacRc4KQnhzqCmPUPb862lUwpIoKashHEd1qlHOAGgA44KYV92b6CNqRAZgy3iTkBg+bsRCPSAfLIZBPQSScMdbU2CrYjAgCyfSr0Qa4RvHo4TMXUT1zZKdfjqdi+cNGBAZQQaWvRZ1LE3IOfqaBsVVtvapcQgdH8KC9ad+a25z9Pl3ZZswm0nZVVSJSgRWz3vELYX2nRHnU5o/JkecN3TbEOnwNNm33B30aWmcrW+EUYrgJ/ycNXtvN8nUxsMEI1GrlyC911zLnSCKLMHd6oX9V+jGVljoG3Efz+aE9K2qmu3Eg7vrmXhWDA003spsUJRAwI/cr4Mces8xFT3gGOJaCCysBkYLuRcSiMUurfECA1qvH+X5Hx5aRO0b/P9jm/JU6GOcqCJFgGG5SgE/yjyemXGtXH5PT5H8egdk8e0rQoe2xqeRILUJLlEE
  app: '$HEROKU_APP_NAME'
  on:
    branch: master
